{% set version = "3.2.0" %}

package:
  name: pytest-benchmark
  version: {{ version }}

source:
  fn: pytest-benchmark-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest-benchmark/pytest-benchmark-{{ version }}.tar.gz
  sha256: 2f84151a6d6b83141b2de71c08a1aef14be393e59e095e3d67fb73caf204c850

build:
  number: 0
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pytest >=2.8
    - py-cpuinfo
    - statistics  # [py<34]
    - pathlib2    # [py<34]

test:
  imports:
    - pytest_benchmark
    - pytest_benchmark.storage
  commands:
    - py.test-benchmark help

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD 2-clause
  summary: "A py.test fixture for benchmarking code"

extra:
    recipe-maintainers:
        - juanlu001
