{% set name = "pytest-benchmark" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-benchmark-{{ version }}.tar.gz
  sha256: fb0785b83efe599a6a956361c0691ae1dbb5318018561af10f3e915caa0048d1

build:
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - pytest >=3.8
    - py-cpuinfo

test:
  imports:
    - pytest_benchmark
  commands:
    - pip check
    - py.test-benchmark --help
    - pytest-benchmark --help
  requires:
    - pip

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A py.test fixture for benchmarking code
  dev_url: https://github.com/ionelmc/pytest-benchmark
  doc_url: https://pytest-benchmark.readthedocs.io

extra:
    recipe-maintainers:
        - juanlu001
