{% set version = "3.4.1" %}

package:
  name: pytest-benchmark
  version: {{ version }}

source:
  fn: pytest-benchmark-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest-benchmark/pytest-benchmark-{{ version }}.tar.gz
  sha256: 40e263f912de5a81d891619032983557d62a3d85843f9a9f30b98baea0cd7b47

build:
  number: 2
  skip: True  # [py<36]
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pytest >=3.8
    - py-cpuinfo

test:
  requires:
    - pip
  imports:
    - pytest_benchmark
    - pytest_benchmark.storage
  commands:
    - pip check
    - py.test-benchmark help

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD-2-Clause
  license_family: BSD
  license_url: https://github.com/ionelmc/pytest-benchmark/blob/master/LICENSE
  license_file: LICENSE
  summary: "A py.test fixture for benchmarking code"
  dev_url: https://github.com/ionelmc/pytest-benchmark
  doc_url: https://pytest-benchmark.readthedocs.io/en/stable/
  doc_source_url: https://pytest-benchmark.readthedocs.io/en/stable/_sources/index.rst.txt

extra:
    recipe-maintainers:
        - juanlu001
