{% set name = "pytest-benchmark" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-benchmark-{{ version }}.tar.gz
  sha256: fb0785b83efe599a6a956361c0691ae1dbb5318018561af10f3e915caa0048d1

build:
  skip: true # [py>37]
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 2

requirements:
  host:
    - python
    - setuptools >=30.3.0
    - wheel
    - pip
    - py
  run:
    - python
    - pytest >=3.8
    - py-cpuinfo
    - py

test:
  imports:
    - pytest_benchmark
  commands:
    - pip check
    - py.test-benchmark --help
    - pytest-benchmark --help
  requires:
    - pip

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pytest fixture for benchmarking code
  description: |
    A pytest fixture for benchmarking code. It will group the tests by the fixture name and will run them with different number of iterations. It will also group the tests by the fixture name and will run them with different number of iterations. It will also group the tests by the fixture name and will run them with different number of iterations. It will also group the tests by the fixture name and will run them with different number of iterations.
  dev_url: https://github.com/ionelmc/pytest-benchmark
  doc_url: https://pytest-benchmark.readthedocs.io

extra:
    recipe-maintainers:
        - juanlu001
