{% set version = "6.0.1" %}

package:
  name: pytest-benchmark
  version: {{ version }}

source:
  fn: pytest-benchmark-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest-benchmark/pytest-benchmark-{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  number: 0
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pytest >=3.8
    - py-cpuinfo
    - statistics  # [py<34]
    - pathlib2    # [py<34]

test:
  imports:
    - pytest_benchmark
    - pytest_benchmark.storage
  commands:
    - py.test-benchmark help

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD 2-clause
  summary: "A py.test fixture for benchmarking code"

extra:
    recipe-maintainers:
        - juanlu001
