{% set name = "pytest-benchmark" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-benchmark-{{ version }}.tar.gz
  sha256: 9ea661cdc292e8231f7cd4c10b0319e56a2118e2c09d9f50e1b3d150d2aca105

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - py.test-benchmark = pytest_benchmark.cli:main
    - pytest-benchmark = pytest_benchmark.cli:main

requirements:
  host:
    - python
    - setuptools >=30.3.0
    - wheel
    - pip
  run:
    - python
    - pytest >=8.1
    - py-cpuinfo

test:
  imports:
    - pytest_benchmark
  requires:
    - pip
  commands:
    - pip check
    - py.test-benchmark --help
    - pytest-benchmark --help

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pytest fixture for benchmarking code
  description: |
    A pytest fixture for benchmarking code. It will group the tests by the fixture name and will run them with different number of iterations. It will also group the tests by the fixture name and will run them with different number of iterations. It will also group the tests by the fixture name and will run them with different number of iterations. It will also group the tests by the fixture name and will run them with different number of iterations.
  dev_url: https://github.com/ionelmc/pytest-benchmark
  doc_url: https://pytest-benchmark.readthedocs.io

extra:
    recipe-maintainers:
        - juanlu001
