# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ACsB5yAKHYIOHgq+3qOv6vs1gEzfOJaISoDCNSug4BqexjCZqvvEbqo2CSHvPQma3UZsyNrNoaSflzPV3fYUGT8LIkgqAE21b+WS1QVBxmqRJUmbGNz/qLJ7JdBFe3YqkDDeh+48v4H9S7zfNm2ZWhrojJnputH8v/fvPfMi77Fi2ZWLxP+6SqZit8TG6N0Azyb5OqIsyTlblf67cJNcfTMYa13xuOxbN3WDSCZwdI+oQqQiN+g1uki9WEcwQV46fdqezZPT6HJodOs8ZgF/XHJFVeLbR5Abcv4RhX3IugtjsZTbCHkiU6kcb9bAdpDiRbztitghuOxJ/T67Bcj5QMUfpM8iSZvyxWzELirj4LJUtj51RPlvJQAOV7B2+NF6mYUUgArM8YRDdLcMEZeNMgshsOLKgC5yVZtOXSIybPy0wANfebkx6oES+KMIDH6DjQSQgimg7LXjCQCyluoLhcVZaWhJxznwPrB4jeZoKMFvRntKkh9gCjv5LwGN6S/r4gWl4/0ipXc6NYgc8Qpg/wA6aIlW4kTIzr+NHDMtRe0moc0IPgOP20Yvsy5wdIVp8T4u2oprbWzZijv01f06+ZK6M00vcU35uxVbVppRRzuRU3SHdKXb0uBUViu39n8otgQhpdQjBNQoi+HD5+lnevlQ4ULnu4XqobKPqeE8xsk="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
