travis:
  secure:
    BINSTAR_TOKEN: ACsB5yAKHYIOHgq+3qOv6vs1gEzfOJaISoDCNSug4BqexjCZqvvEbqo2CSHvPQma3UZsyNrNoaSflzPV3fYUGT8LIkgqAE21b+WS1QVBxmqRJUmbGNz/qLJ7JdBFe3YqkDDeh+48v4H9S7zfNm2ZWhrojJnputH8v/fvPfMi77Fi2ZWLxP+6SqZit8TG6N0Azyb5OqIsyTlblf67cJNcfTMYa13xuOxbN3WDSCZwdI+oQqQiN+g1uki9WEcwQV46fdqezZPT6HJodOs8ZgF/XHJFVeLbR5Abcv4RhX3IugtjsZTbCHkiU6kcb9bAdpDiRbztitghuOxJ/T67Bcj5QMUfpM8iSZvyxWzELirj4LJUtj51RPlvJQAOV7B2+NF6mYUUgArM8YRDdLcMEZeNMgshsOLKgC5yVZtOXSIybPy0wANfebkx6oES+KMIDH6DjQSQgimg7LXjCQCyluoLhcVZaWhJxznwPrB4jeZoKMFvRntKkh9gCjv5LwGN6S/r4gWl4/0ipXc6NYgc8Qpg/wA6aIlW4kTIzr+NHDMtRe0moc0IPgOP20Yvsy5wdIVp8T4u2oprbWzZijv01f06+ZK6M00vcU35uxVbVppRRzuRU3SHdKXb0uBUViu39n8otgQhpdQjBNQoi+HD5+lnevlQ4ULnu4XqobKPqeE8xsk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
